# Generated by Django 3.1.3 on 2020-11-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201108_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
