# Generated by Django 3.1.3 on 2020-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201109_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/img/designs/'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/img/ingredients/'),
        ),
        migrations.AlterField(
            model_name='recipie',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/img/recipies/'),
        ),
    ]
